# Generated by Django 3.2.9 on 2021-12-23 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211223_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address1',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='student',
            name='address2',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='student',
            name='contact_number_1',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='contact_number_2',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('father_email', models.EmailField(blank=True, max_length=254)),
                ('mother_email', models.EmailField(blank=True, max_length=254)),
                ('parent_contact_number_1', models.IntegerField(default=0)),
                ('parent_contact_number_2', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
    ]
