# Generated by Django 3.2.9 on 2021-12-23 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_student_blood_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='registration_number_or_usn_number',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='course_enrolled',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.course'),
            preserve_default=False,
        ),
    ]
