# Generated by Django 3.2.9 on 2021-12-23 06:24

from django.db import migrations, models
import django.db.models.deletion
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_student_registration_number_or_usn_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='caste',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_10_result', models.FileField(blank=True, upload_to='documents/None/10', validators=[main.validators.validate_file_extension])),
                ('class_12_result', models.FileField(blank=True, upload_to='documents/None/12', validators=[main.validators.validate_file_extension])),
                ('PAN_Number', models.BigIntegerField(default=0)),
                ('Adhaar_Number', models.BigIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
    ]
