# Generated by Django 3.2.9 on 2021-12-23 06:40

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_document_pan_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='class_10_result',
            field=models.FileField(blank=True, upload_to='documents/<django.db.models.fields.related.ForeignKey>/10', validators=[main.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='document',
            name='class_12_result',
            field=models.FileField(blank=True, upload_to='documents/<django.db.models.fields.related.ForeignKey>/12', validators=[main.validators.validate_file_extension]),
        ),
    ]
