# Generated by Django 3.2.9 on 2021-12-23 06:50

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20211223_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='class_10_result',
            field=models.FileField(blank=True, upload_to='documents/10', validators=[main.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='document',
            name='class_12_result',
            field=models.FileField(blank=True, upload_to='documents/12', validators=[main.validators.validate_file_extension]),
        ),
    ]
