# Generated by Django 3.2.9 on 2021-12-24 15:49

import datetime
from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20211223_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='address1',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, default=datetime.date(2021, 12, 24)),
        ),
    ]
